### ISSUE TITLE
(Planning) As a developer, I would like to create an ER diagram for the system data model so that a sample database can be created based on the model

### ISSUE THREAD

**Issue by YukselKaradeniz** [mageran/musical-score-creator#4]

**Comment by mageran** [comment]
what would you store in that database? Do you wont to have user data, like scores etc?

**Comment by YukselKaradeniz** [comment]
> what would you store in that database? Do you wont to have user data, like scores etc?
Yes I want to store user, music_list and songs datas.

**Comment by YukselKaradeniz** [comment]
![project_er](https://user-images.githubusercontent.com/36471947/72687873-40744300-3b13-11ea-9d38-5ca737eddc2a.png)
